server:  
  port: 8071

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}

zuul:
  ignoredServices: '*'
  routes:
    focus-policy:
      path: /policies/**
      stripPrefix: false
    focus-claim: 
      path: /claims/**
      stripPrefix: false