server:  
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/focus
    username: focus
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
